"""edit models and clear migrations

Revision ID: 417e84fadddb
Revises: 
Create Date: 2019-08-13 22:47:23.462259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '417e84fadddb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('base_decors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('decorname', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_base_decors_decorname'), 'base_decors', ['decorname'], unique=True)
    op.create_table('second_decors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('decorname', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_second_decors_decorname'), 'second_decors', ['decorname'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('zakaz',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zakaz_timestamp'), 'zakaz', ['timestamp'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zakaz_id', sa.Integer(), nullable=True),
    sa.Column('room', sa.String(length=140), nullable=True),
    sa.ForeignKeyConstraint(['zakaz_id'], ['zakaz.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_timestamp'), 'post', ['timestamp'], unique=False)
    op.create_table('block',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('thickness', sa.Integer(), nullable=True),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('door_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modelname', sa.String(length=64), nullable=True),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.Column('basedecor_id', sa.Integer(), nullable=True),
    sa.Column('seconddecor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['basedecor_id'], ['base_decors.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ),
    sa.ForeignKeyConstraint(['seconddecor_id'], ['second_decors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_door_models_modelname'), 'door_models', ['modelname'], unique=True)
    op.create_table('lutka_var',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lutkaname', sa.String(length=64), nullable=True),
    sa.Column('thickness', sa.Integer(), nullable=True),
    sa.Column('paz', sa.String(length=64), nullable=True),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lutka_var')
    op.drop_index(op.f('ix_door_models_modelname'), table_name='door_models')
    op.drop_table('door_models')
    op.drop_table('block')
    op.drop_index(op.f('ix_post_timestamp'), table_name='post')
    op.drop_table('post')
    op.drop_table('positions')
    op.drop_index(op.f('ix_zakaz_timestamp'), table_name='zakaz')
    op.drop_table('zakaz')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_second_decors_decorname'), table_name='second_decors')
    op.drop_table('second_decors')
    op.drop_index(op.f('ix_base_decors_decorname'), table_name='base_decors')
    op.drop_table('base_decors')
    # ### end Alembic commands ###
