"""add def glass

Revision ID: 6fb0e67d911b
Revises: 003d6a443fa6
Create Date: 2019-08-25 07:55:32.780614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fb0e67d911b'
down_revision = '003d6a443fa6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('second_decors', sa.Column('indexname', sa.String(length=16), nullable=True))
    op.create_index(op.f('ix_second_decors_indexname'), 'second_decors', ['indexname'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_second_decors_indexname'), table_name='second_decors')
    op.drop_column('second_decors', 'indexname')
    # ### end Alembic commands ###
